# Generated by Django 4.2.4 on 2023-08-11 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('members', models.ManyToManyField(related_name='available_events', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('moderators', models.ManyToManyField(related_name='moderated_events', to=settings.AUTH_USER_MODEL, verbose_name='Moderators')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_events', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
