# Generated by Django 4.2.4 on 2023-08-16 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_achievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='challenge_groups',
            field=models.ManyToManyField(blank=True, related_name='events', to='challenges.challengegroup', verbose_name='Challenge groups'),
        ),
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='available_events', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='event',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_events', to=settings.AUTH_USER_MODEL, verbose_name='Moderators'),
        ),
    ]
