from .challenge_complete import ChallengeCompleteView
from .challenge_create import ChallengeCreateView
from .challenge_detail import ChallengeDetailView
from .challenge_list import ChallengeListView
from .favorite_group_add import FavoriteGroupAddView
from .favorite_groups_remove import FavoriteGroupRemoveView
from .group_create import ChallengeGroupCreateView
from .group_detail import ChallengeGroupDetailView
from .group_update import ChallengeGroupUpdateView
