# Generated by Django 4.2.4 on 2023-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_achievement'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_groups',
            field=models.ManyToManyField(to='challenges.challengegroup', verbose_name='Favorite challenge groups'),
        ),
    ]
