# Generated by Django 4.2.4 on 2023-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_challenge_groups_alter_event_members_and_more'),
        ('challenges', '0002_achievement'),
        ('users', '0002_user_favorite_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passed_events',
            field=models.ManyToManyField(blank=True, help_text='Event for each achievement of user.', related_name='attendees', through='challenges.Achievement', to='events.event', verbose_name='Passed events'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_groups',
            field=models.ManyToManyField(blank=True, to='challenges.challengegroup', verbose_name='Favorite challenge groups'),
        ),
    ]
