# Generated by Django 4.2.4 on 2023-08-15 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ChallengeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_groups', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Challenge group',
                'verbose_name_plural': 'Challenge groups',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('prize', models.TextField(blank=True, verbose_name='Prize')),
                ('is_conveyable', models.BooleanField(default=False, help_text='Can challenge be conveyed.', verbose_name='Is conveyable')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('groups', models.ManyToManyField(related_name='challenges', to='challenges.challengegroup', verbose_name='Groups')),
                ('tags', models.ManyToManyField(blank=True, related_name='challenges', to='challenges.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
    ]
