# Generated by Django 4.2.4 on 2023-08-16 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_approved', models.BooleanField(default=False, help_text='Is approved by moderator', verbose_name='Is approved')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='challenges.challenge', verbose_name='Challenge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'unique_together': {('user', 'challenge', 'event')},
            },
        ),
    ]
