# Generated by Django 4.2.4 on 2023-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_groups_challengegroup_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengegroup',
            name='challenges',
            field=models.ManyToManyField(blank=True, related_name='groups', related_query_name='group', to='challenges.challenge', verbose_name='Challenges'),
        ),
    ]
